{% set version = "0.3-28" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-adespatial
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/adespatial_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/adespatial/adespatial_{{ version }}.tar.gz
  sha256: 564548c44eedee7b8820d0b8729524719acba4dea73f549918dcc13dc312a299

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}       # [build_platform != target_platform]
    - {{ compiler('c') }}             # [not win]
    - {{ stdlib("c") }}               # [not win]
    - {{ compiler('m2w64_c') }}       # [win]
    - {{ stdlib("m2w64_c") }}         # [win]
    - {{ compiler('fortran') }}       # [not win]
    - {{ compiler('m2w64_fortran') }} # [win]
    - {{ posix }}filesystem           # [win]
    - {{ posix }}make
    - {{ posix }}sed                  # [win]
    - {{ posix }}coreutils            # [win]
    - {{ posix }}zip                  # [win]
  host:
    - r-base
    - r-ade4 >=1.7_13
    - r-adegraphics
    - r-adephylo
    - r-sp
    - r-spdep
    - r-lattice
    - r-mass
    - r-shiny
    - r-vegan
    - libblas
    - liblapack
  run:
    - r-base
    - r-ade4 >=1.7_13
    - r-adegraphics
    - r-adephylo
    - r-sp
    - r-spdep
    - r-lattice
    - r-mass
    - r-shiny
    - r-vegan

test:
  commands:
    - $R -e "library('adespatial')"           # [not win]
    - "\"%R%\" -e \"library('adespatial')\""  # [win]

about:
  home: http://adeverse.github.io/adespatial/
  dev_url: https://github.com/sdray/adespatial
  license: GPL-2.0-or-later
  summary: Tools for the multiscale spatial analysis of multivariate data. Several methods are based on the use of a spatial weighting matrix and its eigenvector decomposition (Moran's Eigenvectors Maps, MEM). Several approaches are described in the review Dray et al (2012) <doi:10.1890/11-1183.1>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - colineroyaux
